# Generated by Django 4.0.4 on 2022-06-15 06:38

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='DataCamera',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Company', models.CharField(max_length=10)),
                ('name', models.CharField(max_length=255)),
                ('date', models.CharField(blank=True, max_length=255, null=True)),
                ('time_in', models.CharField(blank=True, max_length=255, null=True)),
                ('time_out', models.CharField(blank=True, max_length=255, null=True)),
                ('stack', models.IntegerField()),
                ('image_name', models.CharField(max_length=255)),
            ],
        ),
    ]
